on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 8
        - java: 21
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - uses: sbt/setup-sbt@v1
    - run: sbt -v
           "all scalafmtSbtCheck scalafmtCheckAll scalafixCheckAll scalafixConfigRuleNamesSortCheck"
           test
           scripted
